name: flutter_geopackage
description: A module to support OGC geopackage with sqlite.
version: 0.6.1
homepage: https://github.com/moovida/flutter_geopackage
repository: https://github.com/moovida/flutter_geopackage
issue_tracker: https://github.com/moovida/flutter_geopackage/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: '>=0.16.1 <=0.17.0'

  # MIT -> added to help chose dart_hydrologis_db the right version for the dev channel
  #        can be removed once null-safety has been reached
  sqlite3: ^1.9.1

  dart_hydrologis_db: ^1.0.1
    # path: ../dart_hydrologis_db/
    #  git:
    #    url: https://github.com/moovida/dart_hydrologis_db.git

  dart_jts: ^0.2.2+3
#    git:
#      url: https://github.com/moovida/dart_jts.git

  # MIT
  proj4dart: ^2.1.0


dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  dart_hydrologis_utils: ^0.6.1

